{-# OPTIONS --without-K --safe #-}

module Tanaka where

open import Prelude

open import Pitch using (Octave)
open import Symbolic hiding (C; D; E; F; G; A; B)

C D E F G A B : Octave → NPitch
C = np C♮ 
D = np D♮
E = np E♮
F = np F♮
G = np G♮
A = np A♮
B = np B♮

-- Example from Tanaka 2022, figure 2
tanaka : List (List NPitch)
tanaka =
  (C 5 ∷ D 5 ∷ A 4 ∷ B 4 ∷ A 4 ∷ F 4 ∷ E 4 ∷ C 5 ∷ B 4 ∷ C 5 ∷ []) ∷
  (C 4 ∷ G 3 ∷ F 3 ∷ E 3 ∷ F 3 ∷ D 3 ∷ G 3 ∷ E 3 ∷ D 3 ∷ C 3 ∷ []) ∷ []

-- Example from Tanaka 2022, figure 3 (less good)
tanakaFig3 : List (List NPitch)
tanakaFig3 =
  (C 5 ∷ B 4 ∷ D 5 ∷ C 5 ∷ C 4 ∷ F 4 ∷ E 4 ∷ C 5 ∷ B 4 ∷ C 5 ∷ []) ∷
  (C 4 ∷ G 3 ∷ F 3 ∷ E 3 ∷ F 3 ∷ D 3 ∷ G 3 ∷ E 3 ∷ D 3 ∷ C 3 ∷ []) ∷ []

-- Generated by 1st species, with start and end notes fixed. CF is lower voice.
tanaka1 : List (List NPitch)
tanaka1 =
  (C 5 ∷ G 5 ∷ A 4 ∷ G 4 ∷ F 4 ∷ G 4 ∷ D 4 ∷ G 3 ∷ G 3 ∷ C 5 ∷ []) ∷
  (C 4 ∷ G 3 ∷ F 3 ∷ E 3 ∷ F 3 ∷ D 3 ∷ G 3 ∷ E 3 ∷ D 3 ∷ C 3 ∷ []) ∷ []

