{-# OPTIONS --erased-cubical --safe #-}

module Tanaka where

open import Prelude

open import Symbolic

-- Example from Tanaka 2022
tanaka : List (NPitch × NPitch)
tanaka =
   (C 5 , C 6) ∷
   (G 4 , D 6) ∷
   (F 4 , A 5) ∷
   (E 4 , B 5) ∷
   (F 4 , A 5) ∷
   (D 4 , F 5) ∷
   (G 4 , E 5) ∷
   (E 4 , C 6) ∷
   (D 4 , B 5) ∷
   (C 4 , C 6) ∷ []

-- Generated by pure 1st species constraints
tanaka1 : List (NPitch × NPitch)
tanaka1 =
   (C 5 , C 6) ∷
   (G 4 , E 6) ∷
   (F 4 , D 6) ∷
   (E 4 , G 5) ∷
   (F 4 , D 5) ∷
   (D 4 , D 5) ∷
   (G 4 , E 5) ∷
   (E 4 , C 5) ∷
   (D 4 , A 5) ∷
   (C 4 , C 6) ∷ []

tanaka? : List (NPitch × NPitch)
tanaka? =
   (C 5 , C 6) ∷
   (G 4 , ?? "?1") ∷
   (F 4 , ?? "?2") ∷
   (E 4 , ?? "?3") ∷
   (F 4 , ?? "?4") ∷
   (D 4 , ?? "?5") ∷
   (G 4 , ?? "?6") ∷
   (E 4 , ?? "?7") ∷
   (D 4 , ?? "?8") ∷
   (C 4 , C 6) ∷ []
