{-# OPTIONS --without-K --safe #-}

module Tanaka where

open import Prelude

open import Symbolic

-- Example from Tanaka 2022, figure 2
tanaka : List (List NPitch)
tanaka =
  (C 6 ∷ D 6 ∷ A 5 ∷ B 5 ∷ A 5 ∷ F 5 ∷ E 5 ∷ C 6 ∷ B 5 ∷ C 6 ∷ []) ∷
  (C 5 ∷ G 4 ∷ F 4 ∷ E 4 ∷ F 4 ∷ D 4 ∷ G 4 ∷ E 4 ∷ D 4 ∷ C 4 ∷ []) ∷ []

-- Example from Tanaka 2022, figure 3 (less good)
tanakaFig3 : List (List NPitch)
tanakaFig3 =
  (C 6 ∷ B 5 ∷ D 6 ∷ C 6 ∷ C 5 ∷ F 5 ∷ E 5 ∷ C 6 ∷ B 5 ∷ C 6 ∷ []) ∷
  (C 5 ∷ G 4 ∷ F 4 ∷ E 4 ∷ F 4 ∷ D 4 ∷ G 4 ∷ E 4 ∷ D 4 ∷ C 4 ∷ []) ∷ []

-- Generated by 1st species, with start and end notes fixed. CF is lower voice.
tanaka1 : List (List NPitch)
tanaka1 =
  (C 6 ∷ G 6 ∷ A 5 ∷ G 5 ∷ F 5 ∷ G 5 ∷ D 5 ∷ G 4 ∷ G 4 ∷ C 6 ∷ []) ∷
  (C 5 ∷ G 4 ∷ F 4 ∷ E 4 ∷ F 4 ∷ D 4 ∷ G 4 ∷ E 4 ∷ D 4 ∷ C 4 ∷ []) ∷ []

